export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CREATE_PERIOD = "CREATE_PERIOD";
export const GET_PERIODS = "GET_PERIODS";
export const GET_PERIOD = "GET_PERIOD";
export const DELETE_PERIOD = "DELETE_PERIOD";
export const PERIOD_LOADING = "PERIOD_LOADING";
export const UPDATE_PERIOD = "UPDATE_PERIOD";

export const CREATE_SHIFT = "CREATE_SHIFT";
export const DELETE_SHIFT = "DELETE_SHIFT";
export const EMAIL_SENT = "EMAIL_SENT";
export const CONFIRM_SUCCESSFUL = "CONFIRM_SUCCESSFUL";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const MODAL_ADD_COMPONENT = "MODAL_ADD_COMPONENT";
export const MODAL_REMOVE_COMPONENT = "MODAL_REMOVE_COMPONENT";
export const MODAL_REPLACE_COMPONENT = "MODAL_REPLACE_COMPONENT";
export const MODAL_PREPEND_COMPONENT = "MODAL_PREPEND_COMPONENT";
export const MODAL_REMOVE_COMPONENT_CONFIRM = "MODAL_REMOVE_COMPONENT_CONFIRM";
export const MODAL_SET_DELAYED_UNMOUNT = "MODAL_SET_DELAYED_UNMOUNT";
